# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_refs', models.FloatField(default=0.0)),
                ('social_words', models.FloatField(default=0.0)),
                ('pos_emo', models.FloatField(default=0.0)),
                ('neg_emo', models.FloatField(default=0.0)),
                ('cog_words', models.FloatField(default=0.0)),
                ('art_words', models.FloatField(default=0.0)),
                ('big_words', models.FloatField(default=0.0)),
                ('curr_location', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=2)),
                ('Age', models.IntegerField(default=0)),
                ('Friends', models.IntegerField(default=0)),
                ('Followers', models.IntegerField(default=0)),
                ('Groups', models.IntegerField(default=0)),
                ('fb_degree', models.FloatField(default=0.0)),
                ('Likes', models.IntegerField(default=0)),
                ('Events', models.IntegerField(default=0)),
                ('photos_tagged_in', models.IntegerField(default=0)),
                ('a_score', models.IntegerField(default=0)),
                ('c_score', models.IntegerField(default=0)),
                ('e_score', models.IntegerField(default=0)),
                ('es_score', models.IntegerField(default=0)),
                ('o_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutputFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_label', models.FloatField(default=0.0)),
                ('scored_label', models.FloatField(default=0.0)),
                ('input_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.InputFeatures')),
            ],
        ),
    ]
