# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_auto_20160330_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputFeatures',
            new_name='InputFeature',
        ),
        migrations.RenameModel(
            old_name='OutputFeatures',
            new_name='OutputFeature',
        ),
    ]
