# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0003_auto_20160330_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfeature',
            name='name',
            field=models.CharField(default='poo', max_length=200),
        ),
    ]
