# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0004_inputfeature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfeature',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Gender',
            field=models.CharField(default='F', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='a_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='c_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='curr_location',
            field=models.CharField(default='Singapore', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='e_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='es_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='fb_degree',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='o_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputfeature',
            name='photos_tagged_in',
            field=models.IntegerField(default=0),
        ),
    ]
