# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0006_inputfeature_photos_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfeature',
            name='name',
            field=models.CharField(default='Your Name Here', max_length=200),
        ),
    ]
