# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0009_auto_20160331_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfeature',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='inputfeature',
            name='curr_location',
        ),
    ]
